"""
Batch script to run RL experiments with multiple fixed random seeds.
Runs the same experiment 10 times with different seeds for statistical validation.
"""
import fire
from scripts.rl import main


def run_batch_experiments(
    pool_capacity: int = 20,
    instruments: str = "csi300",
    alphagpt_init: bool = False,
    use_llm: bool = False,
    drop_rl_n: int = 5,
    steps: int = None,
    llm_every_n_steps: int = 25000,
    feedback_loop: bool = False,
    feedback_iter: int = 3,
    feedback_mode: str = "full"
):
    """
    Run experiments with 10 different fixed random seeds.
    
    :param pool_capacity: Maximum size of the alpha pool
    :param instruments: Stock subset name
    :param alphagpt_init: Use an alpha set pre-generated by LLM as the initial pool
    :param use_llm: Enable LLM usage
    :param drop_rl_n: Drop n worst alphas before invoke the LLM
    :param steps: Total iteration steps
    :param llm_every_n_steps: Invoke LLM every n steps
    :param feedback_loop: Enable initial LLM feedback loop (critique/fix/improve)
    :param feedback_iter: Number of feedback iterations for initial LLM alphas
    :param feedback_mode: Type of feedback loop - 'full' or 'fix-only'
    """
    # Fixed random seeds for 10 runs
    random_seeds = (42, 123, 456, 789, 1011, 1213, 1415, 1617, 1819, 2021)
    
    print(f"""[Batch Runner] Starting batch experiments
    Number of runs: {len(random_seeds)}
    Random seeds: {random_seeds}
    Pool capacity: {pool_capacity}
    Instruments: {instruments}
    Use LLM: {use_llm}
    Feedback loop: {feedback_loop}
    """)
    
    main(
        random_seeds=random_seeds,
        pool_capacity=pool_capacity,
        instruments=instruments,
        alphagpt_init=alphagpt_init,
        use_llm=use_llm,
        drop_rl_n=drop_rl_n,
        steps=steps,
        llm_every_n_steps=llm_every_n_steps,
        feedback_loop=feedback_loop,
        feedback_iter=feedback_iter,
        feedback_mode=feedback_mode
    )


if __name__ == '__main__':
    fire.Fire(run_batch_experiments)
